pluginGroup = com.github.jdami
pluginName = AI Commit Message Generator
pluginRepositoryUrl = https://github.com/jdami/ai-generator-commit-message
pluginVersion = 1.1.0

pluginSinceBuild = 253
pluginUntilBuild = 262.*

platformVersion = 2026.2
javaVersion = 25
gradleVersion = 9.4.1

org.gradle.configuration-cache = true
org.gradle.caching = true
